### ISSUE TITLE
add instructions to install as root

### ISSUE THREAD

**Issue by shoulders** [Froxlor/Documentation#11]
Can you clarify here whether you should use the `root` account or if installing via `sudo` is enough.

As with my other notes, this will really help those newbies coming from a Windows environment.

* **sudo** = raise individual commands to root
* **sudo -s** = To execute as shell and temporarily act as root:
* **su root** = To login as root after password is set: 
* **sudo passwd root** = set root password

[How to login as root in Linux - Ubuntu | Linux in a Minute | ITPro | YouTube](https://www.youtube.com/watch?v=fvNOPHFQACM) - Very easy explanation on how to use root in Ubuntu.

**I would add it in the following section**

https://github.com/Froxlor/Documentation/blob/b71bde406b3cc9689ef1f0c3769239a5a0d036b9/general/installation/apt-package.md?plain=1#L1-L3

**Comment by d00p** [comment]
In my opinion, installing packages and the required permissions and how to obtain these is "general knowledge" and nothing froxlor specific. Also, being a sysadmin-tool, if you need help with "How to login as root in Linux" I personally do not recommend running/maintaining a public server at all
